require "helpers"
require "Component"
require "EntMgr"
require "FreeEventBus"
require "InputSystem"

global PlayerSystem = @record
{
	player: EntId,
	entmgr: *EntMgr,
	free_event_bus: *FreeEventBus,
}

## helpers.using(Component)
## helpers.using(Event)

function PlayerSystem:onKeyPressed(event: *KeyPressed)
	print(event.key)
end

function PlayerSystem:init(
		free_event_bus: *FreeEventBus,
		entmgr: *EntMgr)

	self.free_event_bus = free_event_bus
	self.entmgr = entmgr

	-- spawn player entity
	self.player = self.entmgr:newEntity()
	local cmplist = entmgr:getEnt(self.player)

	local transform = entmgr:addComp(Transform)
	local health = entmgr:addComp(Health)

	self.free_event_bus:subscribeTo(KeyPressed, self, PlayerSystem.onKeyPressed)
end

## helpers.generateCreateFunc(PlayerSystem)


