$ require "common"
$ local ui = require "ui.UI"

@@lpp.import "game/client/editor/MenuBar.lh"

namespace ui
{

/* ----------------------------------------------------------------------------
 */
EditorMenuBar* EditorMenuBar::create(UI& ui, cl::Editor* editor)
{
  auto* menubar = ui.allocateAndInitItem<EditorMenuBar>("editor.menubar"_str);
  if (menubar == nullptr)
    return nullptr;

  menubar->editor = editor;

  @ui.style(menubar, EditorMenuBar, 
  | size: 100% 20
  | background_color: 0x000000ff)

  menubar->layout.sizing = ItemLayout::Sizing::PercentX;
  menubar->size = {100.f, 20.f};

  return menubar;
}

/* ----------------------------------------------------------------------------
 */
void EditorMenuBar::update(UI* ui, UpdateReason reason)
{

}

/* ----------------------------------------------------------------------------
 */
void EditorMenuBar::destroy()
{

}

/* ----------------------------------------------------------------------------
 */
void EditorMenuBar::evaluate(UI* ui)
{
  
}

/* ----------------------------------------------------------------------------
 */
void EditorMenuBar::generate(UI* ui)
{
  
}

/* ----------------------------------------------------------------------------
 */
void EditorMenuBar::reportDrawCmds(UI* ui, DrawCmdLists& lists)
{
  
}

}
