/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 71
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 35
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_document = 1,
  anon_sym_DOLLAR = 2,
  anon_sym_DOLLAR_DOLLAR_DOLLAR = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  aux_sym_lua_line_token1 = 6,
  anon_sym_LF = 7,
  anon_sym_COMMA = 8,
  anon_sym_LPAREN2 = 9,
  anon_sym_LBRACE = 10,
  anon_sym_RBRACE = 11,
  anon_sym_DQUOTE = 12,
  anon_sym_DQUOTE2 = 13,
  anon_sym_DOT = 14,
  anon_sym_COLON = 15,
  sym_macro_phase2 = 16,
  sym_macro_phase3 = 17,
  sym__identifier = 18,
  sym_source_file = 19,
  sym__lua = 20,
  sym_lua_line = 21,
  sym_lua_block = 22,
  sym_lua_inline = 23,
  sym_macro = 24,
  sym_macro_tuple_args = 25,
  sym_macro_tuple_arg = 26,
  aux_sym__macro_tuple_arg_nest = 27,
  sym_macro_string_arg = 28,
  sym_macro_identifier = 29,
  sym_macro_identifier_part = 30,
  aux_sym_source_file_repeat1 = 31,
  aux_sym_lua_line_repeat1 = 32,
  aux_sym_macro_tuple_args_repeat1 = 33,
  aux_sym_macro_identifier_repeat1 = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_document] = "document",
  [anon_sym_DOLLAR] = "operator",
  [anon_sym_DOLLAR_DOLLAR_DOLLAR] = "operator",
  [anon_sym_LPAREN] = "punc_bracket",
  [anon_sym_RPAREN] = ")",
  [aux_sym_lua_line_token1] = "lua_line_token1",
  [anon_sym_LF] = "\n",
  [anon_sym_COMMA] = "operator",
  [anon_sym_LPAREN2] = "(",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_DQUOTE2] = "\"",
  [anon_sym_DOT] = "operator",
  [anon_sym_COLON] = "operator",
  [sym_macro_phase2] = "macro_phase2",
  [sym_macro_phase3] = "macro_phase3",
  [sym__identifier] = "_identifier",
  [sym_source_file] = "source_file",
  [sym__lua] = "_lua",
  [sym_lua_line] = "lua_line",
  [sym_lua_block] = "lua_block",
  [sym_lua_inline] = "lua_inline",
  [sym_macro] = "macro",
  [sym_macro_tuple_args] = "macro_tuple_args",
  [sym_macro_tuple_arg] = "macro_tuple_arg",
  [aux_sym__macro_tuple_arg_nest] = "_macro_tuple_arg_nest",
  [sym_macro_string_arg] = "macro_string_arg",
  [sym_macro_identifier] = "macro_identifier",
  [sym_macro_identifier_part] = "macro_identifier_part",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_lua_line_repeat1] = "lua_line_repeat1",
  [aux_sym_macro_tuple_args_repeat1] = "macro_tuple_args_repeat1",
  [aux_sym_macro_identifier_repeat1] = "macro_identifier_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_document] = sym_document,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_DOLLAR_DOLLAR_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_lua_line_token1] = aux_sym_lua_line_token1,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_COMMA] = anon_sym_DOLLAR,
  [anon_sym_LPAREN2] = anon_sym_LPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_DQUOTE2] = anon_sym_DQUOTE,
  [anon_sym_DOT] = anon_sym_DOLLAR,
  [anon_sym_COLON] = anon_sym_DOLLAR,
  [sym_macro_phase2] = sym_macro_phase2,
  [sym_macro_phase3] = sym_macro_phase3,
  [sym__identifier] = sym__identifier,
  [sym_source_file] = sym_source_file,
  [sym__lua] = sym__lua,
  [sym_lua_line] = sym_lua_line,
  [sym_lua_block] = sym_lua_block,
  [sym_lua_inline] = sym_lua_inline,
  [sym_macro] = sym_macro,
  [sym_macro_tuple_args] = sym_macro_tuple_args,
  [sym_macro_tuple_arg] = sym_macro_tuple_arg,
  [aux_sym__macro_tuple_arg_nest] = aux_sym__macro_tuple_arg_nest,
  [sym_macro_string_arg] = sym_macro_string_arg,
  [sym_macro_identifier] = sym_macro_identifier,
  [sym_macro_identifier_part] = sym_macro_identifier_part,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_lua_line_repeat1] = aux_sym_lua_line_repeat1,
  [aux_sym_macro_tuple_args_repeat1] = aux_sym_macro_tuple_args_repeat1,
  [aux_sym_macro_identifier_repeat1] = aux_sym_macro_identifier_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR_DOLLAR_DOLLAR] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_lua_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_phase2] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_phase3] = {
    .visible = true,
    .named = true,
  },
  [sym__identifier] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__lua] = {
    .visible = false,
    .named = true,
  },
  [sym_lua_line] = {
    .visible = true,
    .named = true,
  },
  [sym_lua_block] = {
    .visible = true,
    .named = true,
  },
  [sym_lua_inline] = {
    .visible = true,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_tuple_args] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_tuple_arg] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__macro_tuple_arg_nest] = {
    .visible = false,
    .named = false,
  },
  [sym_macro_string_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_identifier_part] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_lua_line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_macro_tuple_args_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_macro_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [3] = anon_sym_LPAREN,
  },
  [2] = {
    [1] = anon_sym_LPAREN,
  },
  [3] = {
    [2] = anon_sym_LPAREN,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 6,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 22,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 28,
  [34] = 34,
  [35] = 35,
  [36] = 22,
  [37] = 29,
  [38] = 30,
  [39] = 32,
  [40] = 28,
  [41] = 29,
  [42] = 30,
  [43] = 32,
  [44] = 44,
  [45] = 35,
  [46] = 31,
  [47] = 31,
  [48] = 35,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 53,
  [57] = 53,
  [58] = 53,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '"', 42,
        '$', 20,
        '(', 22,
        ')', 23,
        ',', 38,
        '.', 44,
        ':', 45,
        '@', 47,
        '{', 40,
        '}', 41,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == '{') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead == '{') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == '{') ADVANCE(40);
      if (lookahead == '}') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == '{') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '(') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(6);
      if (lookahead == '"') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 7:
      if (lookahead == '\n') SKIP(7);
      if (lookahead == '$') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == '\n') SKIP(8);
      if (lookahead == ')') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 9:
      if (lookahead == '\n') SKIP(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 11:
      if (lookahead == '$') ADVANCE(21);
      END_STATE();
    case 12:
      if (eof) ADVANCE(15);
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '$') ADVANCE(20);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == '.') ADVANCE(44);
      if (lookahead == ':') ADVANCE(45);
      if (lookahead == '@') ADVANCE(47);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 13:
      if (eof) ADVANCE(15);
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '$') ADVANCE(20);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == '@') ADVANCE(47);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '$') ADVANCE(20);
      if (lookahead == '@') ADVANCE(47);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_document);
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == '.') ADVANCE(44);
      if (lookahead == ':') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '@') ADVANCE(19);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_document);
      if (lookahead == '"') ADVANCE(42);
      if (lookahead == '(') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '@') ADVANCE(19);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_document);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '@') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_document);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '@') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '$') ADVANCE(11);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DOLLAR_DOLLAR_DOLLAR);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_lua_line_token1);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_lua_line_token1);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '(') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_lua_line_token1);
      if (lookahead == '\n') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_lua_line_token1);
      if (lookahead == '"') ADVANCE(43);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(24);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_lua_line_token1);
      if (lookahead == '$') ADVANCE(11);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_lua_line_token1);
      if (lookahead == '$') ADVANCE(28);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(24);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_lua_line_token1);
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == ',') ADVANCE(38);
      if (lookahead == '{') ADVANCE(40);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(24);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_lua_line_token1);
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == '{') ADVANCE(40);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(24);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_lua_line_token1);
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == '{') ADVANCE(40);
      if (lookahead == '}') ADVANCE(41);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(24);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_lua_line_token1);
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == '{') ADVANCE(40);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(24);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_lua_line_token1);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(24);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_lua_line_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(24);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '(') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LPAREN2);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DQUOTE2);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_macro_phase2);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_macro_phase3);
      if (lookahead == '@') ADVANCE(46);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym__identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 12},
  [4] = {.lex_state = 12},
  [5] = {.lex_state = 13},
  [6] = {.lex_state = 12},
  [7] = {.lex_state = 12},
  [8] = {.lex_state = 14},
  [9] = {.lex_state = 14},
  [10] = {.lex_state = 13},
  [11] = {.lex_state = 13},
  [12] = {.lex_state = 13},
  [13] = {.lex_state = 14},
  [14] = {.lex_state = 14},
  [15] = {.lex_state = 14},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 14},
  [18] = {.lex_state = 14},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 14},
  [21] = {.lex_state = 14},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 14},
  [24] = {.lex_state = 14},
  [25] = {.lex_state = 14},
  [26] = {.lex_state = 14},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 6},
  [50] = {.lex_state = 7},
  [51] = {.lex_state = 8},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 7},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 9},
  [56] = {.lex_state = 8},
  [57] = {.lex_state = 10},
  [58] = {.lex_state = 6},
  [59] = {.lex_state = 6},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 9},
  [63] = {.lex_state = 10},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_DOLLAR_DOLLAR_DOLLAR] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LPAREN2] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE2] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_macro_phase2] = ACTIONS(1),
    [sym_macro_phase3] = ACTIONS(1),
    [sym__identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(69),
    [sym__lua] = STATE(9),
    [sym_macro] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_document] = ACTIONS(5),
    [anon_sym_DOLLAR] = ACTIONS(7),
    [anon_sym_DOLLAR_DOLLAR_DOLLAR] = ACTIONS(9),
    [sym_macro_phase2] = ACTIONS(11),
    [sym_macro_phase3] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_DOT,
    ACTIONS(19), 1,
      anon_sym_COLON,
    STATE(3), 1,
      aux_sym_macro_identifier_repeat1,
    ACTIONS(15), 7,
      sym_document,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_macro_phase2,
      sym_macro_phase3,
  [22] = 5,
    ACTIONS(17), 1,
      anon_sym_DOT,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      anon_sym_COLON,
    STATE(4), 1,
      aux_sym_macro_identifier_repeat1,
    ACTIONS(23), 7,
      sym_document,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_macro_phase2,
      sym_macro_phase3,
  [44] = 4,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      anon_sym_DOT,
    STATE(4), 1,
      aux_sym_macro_identifier_repeat1,
    ACTIONS(29), 8,
      sym_document,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_COLON,
      sym_macro_phase2,
      sym_macro_phase3,
  [64] = 5,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    ACTIONS(38), 1,
      anon_sym_LPAREN,
    ACTIONS(40), 1,
      anon_sym_DQUOTE,
    STATE(18), 2,
      sym_macro_tuple_args,
      sym_macro_string_arg,
    ACTIONS(36), 5,
      sym_document,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [85] = 2,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
    ACTIONS(44), 9,
      sym_document,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_DOT,
      anon_sym_COLON,
      sym_macro_phase2,
      sym_macro_phase3,
  [100] = 2,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 9,
      sym_document,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_DOT,
      anon_sym_COLON,
      sym_macro_phase2,
      sym_macro_phase3,
  [115] = 6,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    ACTIONS(48), 1,
      sym_document,
    ACTIONS(51), 1,
      anon_sym_DOLLAR,
    ACTIONS(54), 1,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
    ACTIONS(57), 2,
      sym_macro_phase2,
      sym_macro_phase3,
    STATE(8), 3,
      sym__lua,
      sym_macro,
      aux_sym_source_file_repeat1,
  [137] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(9), 1,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(62), 1,
      sym_document,
    ACTIONS(11), 2,
      sym_macro_phase2,
      sym_macro_phase3,
    STATE(8), 3,
      sym__lua,
      sym_macro,
      aux_sym_source_file_repeat1,
  [159] = 2,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    ACTIONS(66), 7,
      sym_document,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_macro_phase2,
      sym_macro_phase3,
  [172] = 2,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    ACTIONS(70), 7,
      sym_document,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_macro_phase2,
      sym_macro_phase3,
  [185] = 2,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
    ACTIONS(44), 7,
      sym_document,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_macro_phase2,
      sym_macro_phase3,
  [198] = 2,
    ACTIONS(72), 2,
      ts_builtin_sym_end,
      sym_document,
    ACTIONS(74), 4,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [209] = 2,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      sym_document,
    ACTIONS(78), 4,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [220] = 2,
    ACTIONS(80), 2,
      ts_builtin_sym_end,
      sym_document,
    ACTIONS(82), 4,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [231] = 6,
    ACTIONS(84), 1,
      anon_sym_RPAREN,
    ACTIONS(86), 1,
      aux_sym_lua_line_token1,
    ACTIONS(88), 1,
      anon_sym_LPAREN2,
    ACTIONS(90), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      aux_sym__macro_tuple_arg_nest,
    STATE(61), 1,
      sym_macro_tuple_arg,
  [250] = 2,
    ACTIONS(92), 2,
      ts_builtin_sym_end,
      sym_document,
    ACTIONS(94), 4,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [261] = 2,
    ACTIONS(96), 2,
      ts_builtin_sym_end,
      sym_document,
    ACTIONS(98), 4,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [272] = 5,
    ACTIONS(88), 1,
      anon_sym_LPAREN2,
    ACTIONS(90), 1,
      anon_sym_LBRACE,
    ACTIONS(102), 1,
      aux_sym_lua_line_token1,
    STATE(22), 1,
      aux_sym__macro_tuple_arg_nest,
    ACTIONS(100), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [289] = 2,
    ACTIONS(104), 2,
      ts_builtin_sym_end,
      sym_document,
    ACTIONS(106), 4,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [300] = 2,
    ACTIONS(108), 2,
      ts_builtin_sym_end,
      sym_document,
    ACTIONS(110), 4,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [311] = 5,
    ACTIONS(114), 1,
      aux_sym_lua_line_token1,
    ACTIONS(117), 1,
      anon_sym_LPAREN2,
    ACTIONS(120), 1,
      anon_sym_LBRACE,
    STATE(22), 1,
      aux_sym__macro_tuple_arg_nest,
    ACTIONS(112), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [328] = 2,
    ACTIONS(123), 2,
      ts_builtin_sym_end,
      sym_document,
    ACTIONS(125), 4,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [339] = 2,
    ACTIONS(127), 2,
      ts_builtin_sym_end,
      sym_document,
    ACTIONS(129), 4,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [350] = 2,
    ACTIONS(131), 2,
      ts_builtin_sym_end,
      sym_document,
    ACTIONS(133), 4,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [361] = 2,
    ACTIONS(135), 2,
      ts_builtin_sym_end,
      sym_document,
    ACTIONS(137), 4,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [372] = 5,
    ACTIONS(112), 1,
      anon_sym_RBRACE,
    ACTIONS(139), 1,
      aux_sym_lua_line_token1,
    ACTIONS(142), 1,
      anon_sym_LPAREN2,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    STATE(27), 1,
      aux_sym__macro_tuple_arg_nest,
  [388] = 5,
    ACTIONS(148), 1,
      aux_sym_lua_line_token1,
    ACTIONS(150), 1,
      anon_sym_LPAREN2,
    ACTIONS(152), 1,
      anon_sym_LBRACE,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
    STATE(27), 1,
      aux_sym__macro_tuple_arg_nest,
  [404] = 5,
    ACTIONS(156), 1,
      anon_sym_RPAREN,
    ACTIONS(158), 1,
      aux_sym_lua_line_token1,
    ACTIONS(160), 1,
      anon_sym_LPAREN2,
    ACTIONS(162), 1,
      anon_sym_LBRACE,
    STATE(32), 1,
      aux_sym__macro_tuple_arg_nest,
  [420] = 5,
    ACTIONS(150), 1,
      anon_sym_LPAREN2,
    ACTIONS(152), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      anon_sym_RBRACE,
    ACTIONS(164), 1,
      aux_sym_lua_line_token1,
    STATE(33), 1,
      aux_sym__macro_tuple_arg_nest,
  [436] = 1,
    ACTIONS(112), 5,
      anon_sym_RPAREN,
      aux_sym_lua_line_token1,
      anon_sym_COMMA,
      anon_sym_LPAREN2,
      anon_sym_LBRACE,
  [444] = 5,
    ACTIONS(160), 1,
      anon_sym_LPAREN2,
    ACTIONS(162), 1,
      anon_sym_LBRACE,
    ACTIONS(166), 1,
      anon_sym_RPAREN,
    ACTIONS(168), 1,
      aux_sym_lua_line_token1,
    STATE(36), 1,
      aux_sym__macro_tuple_arg_nest,
  [460] = 5,
    ACTIONS(148), 1,
      aux_sym_lua_line_token1,
    ACTIONS(150), 1,
      anon_sym_LPAREN2,
    ACTIONS(152), 1,
      anon_sym_LBRACE,
    ACTIONS(166), 1,
      anon_sym_RBRACE,
    STATE(27), 1,
      aux_sym__macro_tuple_arg_nest,
  [476] = 5,
    ACTIONS(86), 1,
      aux_sym_lua_line_token1,
    ACTIONS(88), 1,
      anon_sym_LPAREN2,
    ACTIONS(90), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      aux_sym__macro_tuple_arg_nest,
    STATE(65), 1,
      sym_macro_tuple_arg,
  [492] = 1,
    ACTIONS(170), 5,
      anon_sym_RPAREN,
      aux_sym_lua_line_token1,
      anon_sym_COMMA,
      anon_sym_LPAREN2,
      anon_sym_LBRACE,
  [500] = 5,
    ACTIONS(112), 1,
      anon_sym_RPAREN,
    ACTIONS(172), 1,
      aux_sym_lua_line_token1,
    ACTIONS(175), 1,
      anon_sym_LPAREN2,
    ACTIONS(178), 1,
      anon_sym_LBRACE,
    STATE(36), 1,
      aux_sym__macro_tuple_arg_nest,
  [516] = 5,
    ACTIONS(160), 1,
      anon_sym_LPAREN2,
    ACTIONS(162), 1,
      anon_sym_LBRACE,
    ACTIONS(181), 1,
      anon_sym_RPAREN,
    ACTIONS(183), 1,
      aux_sym_lua_line_token1,
    STATE(39), 1,
      aux_sym__macro_tuple_arg_nest,
  [532] = 5,
    ACTIONS(150), 1,
      anon_sym_LPAREN2,
    ACTIONS(152), 1,
      anon_sym_LBRACE,
    ACTIONS(181), 1,
      anon_sym_RBRACE,
    ACTIONS(185), 1,
      aux_sym_lua_line_token1,
    STATE(40), 1,
      aux_sym__macro_tuple_arg_nest,
  [548] = 5,
    ACTIONS(160), 1,
      anon_sym_LPAREN2,
    ACTIONS(162), 1,
      anon_sym_LBRACE,
    ACTIONS(168), 1,
      aux_sym_lua_line_token1,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    STATE(36), 1,
      aux_sym__macro_tuple_arg_nest,
  [564] = 5,
    ACTIONS(148), 1,
      aux_sym_lua_line_token1,
    ACTIONS(150), 1,
      anon_sym_LPAREN2,
    ACTIONS(152), 1,
      anon_sym_LBRACE,
    ACTIONS(187), 1,
      anon_sym_RBRACE,
    STATE(27), 1,
      aux_sym__macro_tuple_arg_nest,
  [580] = 5,
    ACTIONS(160), 1,
      anon_sym_LPAREN2,
    ACTIONS(162), 1,
      anon_sym_LBRACE,
    ACTIONS(189), 1,
      anon_sym_RPAREN,
    ACTIONS(191), 1,
      aux_sym_lua_line_token1,
    STATE(43), 1,
      aux_sym__macro_tuple_arg_nest,
  [596] = 5,
    ACTIONS(150), 1,
      anon_sym_LPAREN2,
    ACTIONS(152), 1,
      anon_sym_LBRACE,
    ACTIONS(189), 1,
      anon_sym_RBRACE,
    ACTIONS(193), 1,
      aux_sym_lua_line_token1,
    STATE(28), 1,
      aux_sym__macro_tuple_arg_nest,
  [612] = 5,
    ACTIONS(154), 1,
      anon_sym_RPAREN,
    ACTIONS(160), 1,
      anon_sym_LPAREN2,
    ACTIONS(162), 1,
      anon_sym_LBRACE,
    ACTIONS(168), 1,
      aux_sym_lua_line_token1,
    STATE(36), 1,
      aux_sym__macro_tuple_arg_nest,
  [628] = 5,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(197), 1,
      aux_sym_lua_line_token1,
    ACTIONS(199), 1,
      anon_sym_LF,
    STATE(14), 1,
      sym_lua_line,
    STATE(63), 1,
      aux_sym_lua_line_repeat1,
  [644] = 1,
    ACTIONS(170), 4,
      anon_sym_RPAREN,
      aux_sym_lua_line_token1,
      anon_sym_LPAREN2,
      anon_sym_LBRACE,
  [651] = 1,
    ACTIONS(112), 4,
      anon_sym_RPAREN,
      aux_sym_lua_line_token1,
      anon_sym_LPAREN2,
      anon_sym_LBRACE,
  [658] = 1,
    ACTIONS(112), 4,
      aux_sym_lua_line_token1,
      anon_sym_LPAREN2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [665] = 1,
    ACTIONS(170), 4,
      aux_sym_lua_line_token1,
      anon_sym_LPAREN2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [672] = 3,
    ACTIONS(201), 1,
      aux_sym_lua_line_token1,
    ACTIONS(203), 1,
      anon_sym_DQUOTE2,
    STATE(59), 1,
      aux_sym_lua_line_repeat1,
  [682] = 3,
    ACTIONS(205), 1,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
    ACTIONS(207), 1,
      aux_sym_lua_line_token1,
    STATE(53), 1,
      aux_sym_lua_line_repeat1,
  [692] = 3,
    ACTIONS(209), 1,
      anon_sym_RPAREN,
    ACTIONS(211), 1,
      aux_sym_lua_line_token1,
    STATE(56), 1,
      aux_sym_lua_line_repeat1,
  [702] = 3,
    ACTIONS(213), 1,
      sym__identifier,
    STATE(2), 1,
      sym_macro_identifier_part,
    STATE(5), 1,
      sym_macro_identifier,
  [712] = 3,
    ACTIONS(215), 1,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
    ACTIONS(217), 1,
      aux_sym_lua_line_token1,
    STATE(53), 1,
      aux_sym_lua_line_repeat1,
  [722] = 3,
    ACTIONS(220), 1,
      anon_sym_RPAREN,
    ACTIONS(222), 1,
      anon_sym_COMMA,
    STATE(54), 1,
      aux_sym_macro_tuple_args_repeat1,
  [732] = 3,
    ACTIONS(225), 1,
      aux_sym_lua_line_token1,
    STATE(51), 1,
      aux_sym_lua_line_repeat1,
    STATE(70), 1,
      sym_lua_inline,
  [742] = 3,
    ACTIONS(215), 1,
      anon_sym_RPAREN,
    ACTIONS(227), 1,
      aux_sym_lua_line_token1,
    STATE(56), 1,
      aux_sym_lua_line_repeat1,
  [752] = 3,
    ACTIONS(215), 1,
      anon_sym_LF,
    ACTIONS(230), 1,
      aux_sym_lua_line_token1,
    STATE(57), 1,
      aux_sym_lua_line_repeat1,
  [762] = 3,
    ACTIONS(215), 1,
      anon_sym_DQUOTE2,
    ACTIONS(233), 1,
      aux_sym_lua_line_token1,
    STATE(58), 1,
      aux_sym_lua_line_repeat1,
  [772] = 3,
    ACTIONS(236), 1,
      aux_sym_lua_line_token1,
    ACTIONS(238), 1,
      anon_sym_DQUOTE2,
    STATE(58), 1,
      aux_sym_lua_line_repeat1,
  [782] = 3,
    ACTIONS(240), 1,
      anon_sym_RPAREN,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    STATE(54), 1,
      aux_sym_macro_tuple_args_repeat1,
  [792] = 3,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    ACTIONS(244), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      aux_sym_macro_tuple_args_repeat1,
  [802] = 3,
    ACTIONS(246), 1,
      aux_sym_lua_line_token1,
    STATE(50), 1,
      aux_sym_lua_line_repeat1,
    STATE(68), 1,
      sym_lua_block,
  [812] = 3,
    ACTIONS(248), 1,
      aux_sym_lua_line_token1,
    ACTIONS(250), 1,
      anon_sym_LF,
    STATE(57), 1,
      aux_sym_lua_line_repeat1,
  [822] = 2,
    ACTIONS(213), 1,
      sym__identifier,
    STATE(7), 1,
      sym_macro_identifier_part,
  [829] = 1,
    ACTIONS(220), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [834] = 2,
    ACTIONS(252), 1,
      sym__identifier,
    STATE(10), 1,
      sym_macro_identifier_part,
  [841] = 2,
    ACTIONS(252), 1,
      sym__identifier,
    STATE(11), 1,
      sym_macro_identifier_part,
  [848] = 1,
    ACTIONS(254), 1,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
  [852] = 1,
    ACTIONS(256), 1,
      ts_builtin_sym_end,
  [856] = 1,
    ACTIONS(258), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 64,
  [SMALL_STATE(6)] = 85,
  [SMALL_STATE(7)] = 100,
  [SMALL_STATE(8)] = 115,
  [SMALL_STATE(9)] = 137,
  [SMALL_STATE(10)] = 159,
  [SMALL_STATE(11)] = 172,
  [SMALL_STATE(12)] = 185,
  [SMALL_STATE(13)] = 198,
  [SMALL_STATE(14)] = 209,
  [SMALL_STATE(15)] = 220,
  [SMALL_STATE(16)] = 231,
  [SMALL_STATE(17)] = 250,
  [SMALL_STATE(18)] = 261,
  [SMALL_STATE(19)] = 272,
  [SMALL_STATE(20)] = 289,
  [SMALL_STATE(21)] = 300,
  [SMALL_STATE(22)] = 311,
  [SMALL_STATE(23)] = 328,
  [SMALL_STATE(24)] = 339,
  [SMALL_STATE(25)] = 350,
  [SMALL_STATE(26)] = 361,
  [SMALL_STATE(27)] = 372,
  [SMALL_STATE(28)] = 388,
  [SMALL_STATE(29)] = 404,
  [SMALL_STATE(30)] = 420,
  [SMALL_STATE(31)] = 436,
  [SMALL_STATE(32)] = 444,
  [SMALL_STATE(33)] = 460,
  [SMALL_STATE(34)] = 476,
  [SMALL_STATE(35)] = 492,
  [SMALL_STATE(36)] = 500,
  [SMALL_STATE(37)] = 516,
  [SMALL_STATE(38)] = 532,
  [SMALL_STATE(39)] = 548,
  [SMALL_STATE(40)] = 564,
  [SMALL_STATE(41)] = 580,
  [SMALL_STATE(42)] = 596,
  [SMALL_STATE(43)] = 612,
  [SMALL_STATE(44)] = 628,
  [SMALL_STATE(45)] = 644,
  [SMALL_STATE(46)] = 651,
  [SMALL_STATE(47)] = 658,
  [SMALL_STATE(48)] = 665,
  [SMALL_STATE(49)] = 672,
  [SMALL_STATE(50)] = 682,
  [SMALL_STATE(51)] = 692,
  [SMALL_STATE(52)] = 702,
  [SMALL_STATE(53)] = 712,
  [SMALL_STATE(54)] = 722,
  [SMALL_STATE(55)] = 732,
  [SMALL_STATE(56)] = 742,
  [SMALL_STATE(57)] = 752,
  [SMALL_STATE(58)] = 762,
  [SMALL_STATE(59)] = 772,
  [SMALL_STATE(60)] = 782,
  [SMALL_STATE(61)] = 792,
  [SMALL_STATE(62)] = 802,
  [SMALL_STATE(63)] = 812,
  [SMALL_STATE(64)] = 822,
  [SMALL_STATE(65)] = 829,
  [SMALL_STATE(66)] = 834,
  [SMALL_STATE(67)] = 841,
  [SMALL_STATE(68)] = 848,
  [SMALL_STATE(69)] = 852,
  [SMALL_STATE(70)] = 856,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_identifier, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_identifier, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_identifier, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_identifier, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_macro_identifier_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_macro_identifier_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_identifier_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 2, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 2, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_identifier_part, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_identifier_part, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_identifier, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_identifier, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_identifier, 4, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_identifier, 4, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lua_line, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lua_line, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lua, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__lua, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lua, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__lua, 3, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lua_line, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lua_line, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_tuple_arg, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_string_arg, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_string_arg, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_tuple_args, 3, 0, 3),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_tuple_args, 3, 0, 3),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 2, 0, 0),
  [114] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 2, 0, 0), SHIFT_REPEAT(22),
  [117] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 2, 0, 0), SHIFT_REPEAT(29),
  [120] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 2, 0, 0), SHIFT_REPEAT(30),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_string_arg, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_string_arg, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_tuple_args, 2, 0, 2),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_tuple_args, 2, 0, 2),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_tuple_args, 4, 0, 1),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_tuple_args, 4, 0, 1),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lua, 4, 0, 1),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__lua, 4, 0, 1),
  [139] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 2, 0, 0), SHIFT_REPEAT(27),
  [142] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 2, 0, 0), SHIFT_REPEAT(41),
  [145] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 2, 0, 0), SHIFT_REPEAT(42),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 3, 0, 0),
  [172] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 2, 0, 0), SHIFT_REPEAT(36),
  [175] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 2, 0, 0), SHIFT_REPEAT(37),
  [178] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 2, 0, 0), SHIFT_REPEAT(38),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lua_block, 1, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lua_inline, 1, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_lua_line_repeat1, 2, 0, 0),
  [217] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_lua_line_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_macro_tuple_args_repeat1, 2, 0, 0),
  [222] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_macro_tuple_args_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [227] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_lua_line_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [230] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_lua_line_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [233] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_lua_line_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [236] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [250] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [256] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lpp(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lpp",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
