/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 67
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_document = 1,
  anon_sym_DOLLAR = 2,
  anon_sym_DOLLAR_DOLLAR_DOLLAR = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  sym_lua_line = 6,
  aux_sym_lua_block_token1 = 7,
  anon_sym_COMMA = 8,
  anon_sym_LPAREN2 = 9,
  anon_sym_LBRACE = 10,
  anon_sym_RBRACE = 11,
  anon_sym_DQUOTE = 12,
  anon_sym_DQUOTE2 = 13,
  anon_sym_DOT = 14,
  anon_sym_COLON = 15,
  sym_macro_phase2 = 16,
  sym_macro_phase3 = 17,
  sym__identifier = 18,
  sym_source_file = 19,
  sym__lua = 20,
  sym_lua_block = 21,
  sym_lua_inline = 22,
  sym_macro = 23,
  sym_macro_tuple_args = 24,
  sym_macro_tuple_arg = 25,
  aux_sym__macro_tuple_arg_nest = 26,
  sym_macro_string_arg = 27,
  sym_macro_identifier = 28,
  sym_macro_identifier_part = 29,
  aux_sym_source_file_repeat1 = 30,
  aux_sym_lua_block_repeat1 = 31,
  aux_sym_macro_tuple_args_repeat1 = 32,
  aux_sym_macro_identifier_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_document] = "document",
  [anon_sym_DOLLAR] = "operator",
  [anon_sym_DOLLAR_DOLLAR_DOLLAR] = "operator",
  [anon_sym_LPAREN] = "punc_bracket",
  [anon_sym_RPAREN] = ")",
  [sym_lua_line] = "lua_line",
  [aux_sym_lua_block_token1] = "lua_block_token1",
  [anon_sym_COMMA] = "operator",
  [anon_sym_LPAREN2] = "(",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_DQUOTE2] = "\"",
  [anon_sym_DOT] = "operator",
  [anon_sym_COLON] = "operator",
  [sym_macro_phase2] = "macro_phase2",
  [sym_macro_phase3] = "macro_phase3",
  [sym__identifier] = "_identifier",
  [sym_source_file] = "source_file",
  [sym__lua] = "_lua",
  [sym_lua_block] = "lua_block",
  [sym_lua_inline] = "lua_inline",
  [sym_macro] = "macro",
  [sym_macro_tuple_args] = "macro_tuple_args",
  [sym_macro_tuple_arg] = "macro_tuple_arg",
  [aux_sym__macro_tuple_arg_nest] = "_macro_tuple_arg_nest",
  [sym_macro_string_arg] = "macro_string_arg",
  [sym_macro_identifier] = "macro_identifier",
  [sym_macro_identifier_part] = "macro_identifier_part",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_lua_block_repeat1] = "lua_block_repeat1",
  [aux_sym_macro_tuple_args_repeat1] = "macro_tuple_args_repeat1",
  [aux_sym_macro_identifier_repeat1] = "macro_identifier_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_document] = sym_document,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_DOLLAR_DOLLAR_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_lua_line] = sym_lua_line,
  [aux_sym_lua_block_token1] = aux_sym_lua_block_token1,
  [anon_sym_COMMA] = anon_sym_DOLLAR,
  [anon_sym_LPAREN2] = anon_sym_LPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_DQUOTE2] = anon_sym_DQUOTE,
  [anon_sym_DOT] = anon_sym_DOLLAR,
  [anon_sym_COLON] = anon_sym_DOLLAR,
  [sym_macro_phase2] = sym_macro_phase2,
  [sym_macro_phase3] = sym_macro_phase3,
  [sym__identifier] = sym__identifier,
  [sym_source_file] = sym_source_file,
  [sym__lua] = sym__lua,
  [sym_lua_block] = sym_lua_block,
  [sym_lua_inline] = sym_lua_inline,
  [sym_macro] = sym_macro,
  [sym_macro_tuple_args] = sym_macro_tuple_args,
  [sym_macro_tuple_arg] = sym_macro_tuple_arg,
  [aux_sym__macro_tuple_arg_nest] = aux_sym__macro_tuple_arg_nest,
  [sym_macro_string_arg] = sym_macro_string_arg,
  [sym_macro_identifier] = sym_macro_identifier,
  [sym_macro_identifier_part] = sym_macro_identifier_part,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_lua_block_repeat1] = aux_sym_lua_block_repeat1,
  [aux_sym_macro_tuple_args_repeat1] = aux_sym_macro_tuple_args_repeat1,
  [aux_sym_macro_identifier_repeat1] = aux_sym_macro_identifier_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR_DOLLAR_DOLLAR] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_lua_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_lua_block_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_phase2] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_phase3] = {
    .visible = true,
    .named = true,
  },
  [sym__identifier] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__lua] = {
    .visible = false,
    .named = true,
  },
  [sym_lua_block] = {
    .visible = true,
    .named = true,
  },
  [sym_lua_inline] = {
    .visible = true,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_tuple_args] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_tuple_arg] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__macro_tuple_arg_nest] = {
    .visible = false,
    .named = false,
  },
  [sym_macro_string_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_identifier_part] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_lua_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_macro_tuple_args_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_macro_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [3] = anon_sym_LPAREN,
  },
  [2] = {
    [1] = anon_sym_LPAREN,
  },
  [3] = {
    [2] = anon_sym_LPAREN,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 5,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 20,
  [32] = 20,
  [33] = 26,
  [34] = 27,
  [35] = 29,
  [36] = 25,
  [37] = 26,
  [38] = 27,
  [39] = 29,
  [40] = 25,
  [41] = 41,
  [42] = 28,
  [43] = 41,
  [44] = 28,
  [45] = 41,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 50,
  [54] = 54,
  [55] = 55,
  [56] = 50,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '"', 40,
        '$', 20,
        '(', 22,
        ')', 23,
        ',', 36,
        '.', 42,
        ':', 43,
        '@', 45,
        '{', 38,
        '}', 39,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '(') ADVANCE(37);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == '{') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '(') ADVANCE(37);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == ',') ADVANCE(36);
      if (lookahead == '{') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '(') ADVANCE(37);
      if (lookahead == '{') ADVANCE(38);
      if (lookahead == '}') ADVANCE(39);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '(') ADVANCE(37);
      if (lookahead == '{') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(5);
      if (lookahead == '$') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(6);
      if (lookahead == ')') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 7:
      if (lookahead == '\n') SKIP(7);
      if (lookahead == '"') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 8:
      if (lookahead == '\n') SKIP(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '(') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == '$') ADVANCE(21);
      END_STATE();
    case 12:
      if (eof) ADVANCE(15);
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '$') ADVANCE(20);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == ':') ADVANCE(43);
      if (lookahead == '@') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 13:
      if (eof) ADVANCE(15);
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '$') ADVANCE(20);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == '@') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '$') ADVANCE(20);
      if (lookahead == '@') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_document);
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == ':') ADVANCE(43);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '@') ADVANCE(19);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_document);
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '(') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '@') ADVANCE(19);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_document);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '@') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_document);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '@') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '$') ADVANCE(11);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DOLLAR_DOLLAR_DOLLAR);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_lua_line);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_lua_line);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '(') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_lua_block_token1);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_lua_block_token1);
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(26);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_lua_block_token1);
      if (lookahead == '$') ADVANCE(11);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_lua_block_token1);
      if (lookahead == '$') ADVANCE(28);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(26);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_lua_block_token1);
      if (lookahead == '(') ADVANCE(37);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == ',') ADVANCE(36);
      if (lookahead == '{') ADVANCE(38);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(26);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_lua_block_token1);
      if (lookahead == '(') ADVANCE(37);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == '{') ADVANCE(38);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(26);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_lua_block_token1);
      if (lookahead == '(') ADVANCE(37);
      if (lookahead == '{') ADVANCE(38);
      if (lookahead == '}') ADVANCE(39);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(26);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_lua_block_token1);
      if (lookahead == '(') ADVANCE(37);
      if (lookahead == '{') ADVANCE(38);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(26);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_lua_block_token1);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(26);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_lua_block_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(26);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LPAREN2);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DQUOTE2);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_macro_phase2);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_macro_phase3);
      if (lookahead == '@') ADVANCE(44);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 12},
  [4] = {.lex_state = 12},
  [5] = {.lex_state = 12},
  [6] = {.lex_state = 13},
  [7] = {.lex_state = 12},
  [8] = {.lex_state = 14},
  [9] = {.lex_state = 14},
  [10] = {.lex_state = 13},
  [11] = {.lex_state = 13},
  [12] = {.lex_state = 13},
  [13] = {.lex_state = 14},
  [14] = {.lex_state = 14},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 14},
  [17] = {.lex_state = 14},
  [18] = {.lex_state = 14},
  [19] = {.lex_state = 14},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 14},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 14},
  [24] = {.lex_state = 14},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 5},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 6},
  [51] = {.lex_state = 7},
  [52] = {.lex_state = 6},
  [53] = {.lex_state = 7},
  [54] = {.lex_state = 8},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 5},
  [57] = {.lex_state = 7},
  [58] = {.lex_state = 8},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 9},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_DOLLAR_DOLLAR_DOLLAR] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LPAREN2] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE2] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_macro_phase2] = ACTIONS(1),
    [sym_macro_phase3] = ACTIONS(1),
    [sym__identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(64),
    [sym__lua] = STATE(8),
    [sym_macro] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_document] = ACTIONS(5),
    [anon_sym_DOLLAR] = ACTIONS(7),
    [anon_sym_DOLLAR_DOLLAR_DOLLAR] = ACTIONS(9),
    [sym_macro_phase2] = ACTIONS(11),
    [sym_macro_phase3] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_DOT,
    ACTIONS(19), 1,
      anon_sym_COLON,
    STATE(3), 1,
      aux_sym_macro_identifier_repeat1,
    ACTIONS(15), 7,
      sym_document,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_macro_phase2,
      sym_macro_phase3,
  [22] = 5,
    ACTIONS(17), 1,
      anon_sym_DOT,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      anon_sym_COLON,
    STATE(4), 1,
      aux_sym_macro_identifier_repeat1,
    ACTIONS(23), 7,
      sym_document,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_macro_phase2,
      sym_macro_phase3,
  [44] = 4,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      anon_sym_DOT,
    STATE(4), 1,
      aux_sym_macro_identifier_repeat1,
    ACTIONS(29), 8,
      sym_document,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_COLON,
      sym_macro_phase2,
      sym_macro_phase3,
  [64] = 2,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    ACTIONS(36), 9,
      sym_document,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_DOT,
      anon_sym_COLON,
      sym_macro_phase2,
      sym_macro_phase3,
  [79] = 5,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
    ACTIONS(42), 1,
      anon_sym_LPAREN,
    ACTIONS(44), 1,
      anon_sym_DQUOTE,
    STATE(16), 2,
      sym_macro_tuple_args,
      sym_macro_string_arg,
    ACTIONS(40), 5,
      sym_document,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [100] = 2,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 9,
      sym_document,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      anon_sym_DOT,
      anon_sym_COLON,
      sym_macro_phase2,
      sym_macro_phase3,
  [115] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(9), 1,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    ACTIONS(48), 1,
      sym_document,
    ACTIONS(11), 2,
      sym_macro_phase2,
      sym_macro_phase3,
    STATE(9), 3,
      sym__lua,
      sym_macro,
      aux_sym_source_file_repeat1,
  [137] = 6,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
    ACTIONS(52), 1,
      sym_document,
    ACTIONS(55), 1,
      anon_sym_DOLLAR,
    ACTIONS(58), 1,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
    ACTIONS(61), 2,
      sym_macro_phase2,
      sym_macro_phase3,
    STATE(9), 3,
      sym__lua,
      sym_macro,
      aux_sym_source_file_repeat1,
  [159] = 2,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    ACTIONS(66), 7,
      sym_document,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_macro_phase2,
      sym_macro_phase3,
  [172] = 2,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    ACTIONS(70), 7,
      sym_document,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_macro_phase2,
      sym_macro_phase3,
  [185] = 2,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    ACTIONS(36), 7,
      sym_document,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      anon_sym_LPAREN,
      anon_sym_DQUOTE,
      sym_macro_phase2,
      sym_macro_phase3,
  [198] = 2,
    ACTIONS(72), 2,
      ts_builtin_sym_end,
      sym_document,
    ACTIONS(74), 4,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [209] = 2,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      sym_document,
    ACTIONS(78), 4,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [220] = 6,
    ACTIONS(80), 1,
      anon_sym_RPAREN,
    ACTIONS(82), 1,
      aux_sym_lua_block_token1,
    ACTIONS(84), 1,
      anon_sym_LPAREN2,
    ACTIONS(86), 1,
      anon_sym_LBRACE,
    STATE(22), 1,
      aux_sym__macro_tuple_arg_nest,
    STATE(55), 1,
      sym_macro_tuple_arg,
  [239] = 2,
    ACTIONS(88), 2,
      ts_builtin_sym_end,
      sym_document,
    ACTIONS(90), 4,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [250] = 2,
    ACTIONS(92), 2,
      ts_builtin_sym_end,
      sym_document,
    ACTIONS(94), 4,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [261] = 2,
    ACTIONS(96), 2,
      ts_builtin_sym_end,
      sym_document,
    ACTIONS(98), 4,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [272] = 2,
    ACTIONS(100), 2,
      ts_builtin_sym_end,
      sym_document,
    ACTIONS(102), 4,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [283] = 5,
    ACTIONS(106), 1,
      aux_sym_lua_block_token1,
    ACTIONS(109), 1,
      anon_sym_LPAREN2,
    ACTIONS(112), 1,
      anon_sym_LBRACE,
    STATE(20), 1,
      aux_sym__macro_tuple_arg_nest,
    ACTIONS(104), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [300] = 2,
    ACTIONS(115), 2,
      ts_builtin_sym_end,
      sym_document,
    ACTIONS(117), 4,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [311] = 5,
    ACTIONS(84), 1,
      anon_sym_LPAREN2,
    ACTIONS(86), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      aux_sym_lua_block_token1,
    STATE(20), 1,
      aux_sym__macro_tuple_arg_nest,
    ACTIONS(119), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [328] = 2,
    ACTIONS(123), 2,
      ts_builtin_sym_end,
      sym_document,
    ACTIONS(125), 4,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [339] = 2,
    ACTIONS(127), 2,
      ts_builtin_sym_end,
      sym_document,
    ACTIONS(129), 4,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
      sym_macro_phase2,
      sym_macro_phase3,
  [350] = 5,
    ACTIONS(131), 1,
      aux_sym_lua_block_token1,
    ACTIONS(133), 1,
      anon_sym_LPAREN2,
    ACTIONS(135), 1,
      anon_sym_LBRACE,
    ACTIONS(137), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      aux_sym__macro_tuple_arg_nest,
  [366] = 5,
    ACTIONS(139), 1,
      anon_sym_RPAREN,
    ACTIONS(141), 1,
      aux_sym_lua_block_token1,
    ACTIONS(143), 1,
      anon_sym_LPAREN2,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    STATE(29), 1,
      aux_sym__macro_tuple_arg_nest,
  [382] = 5,
    ACTIONS(133), 1,
      anon_sym_LPAREN2,
    ACTIONS(135), 1,
      anon_sym_LBRACE,
    ACTIONS(139), 1,
      anon_sym_RBRACE,
    ACTIONS(147), 1,
      aux_sym_lua_block_token1,
    STATE(25), 1,
      aux_sym__macro_tuple_arg_nest,
  [398] = 1,
    ACTIONS(104), 5,
      anon_sym_RPAREN,
      aux_sym_lua_block_token1,
      anon_sym_COMMA,
      anon_sym_LPAREN2,
      anon_sym_LBRACE,
  [406] = 5,
    ACTIONS(137), 1,
      anon_sym_RPAREN,
    ACTIONS(143), 1,
      anon_sym_LPAREN2,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    ACTIONS(149), 1,
      aux_sym_lua_block_token1,
    STATE(31), 1,
      aux_sym__macro_tuple_arg_nest,
  [422] = 5,
    ACTIONS(82), 1,
      aux_sym_lua_block_token1,
    ACTIONS(84), 1,
      anon_sym_LPAREN2,
    ACTIONS(86), 1,
      anon_sym_LBRACE,
    STATE(22), 1,
      aux_sym__macro_tuple_arg_nest,
    STATE(61), 1,
      sym_macro_tuple_arg,
  [438] = 5,
    ACTIONS(104), 1,
      anon_sym_RPAREN,
    ACTIONS(151), 1,
      aux_sym_lua_block_token1,
    ACTIONS(154), 1,
      anon_sym_LPAREN2,
    ACTIONS(157), 1,
      anon_sym_LBRACE,
    STATE(31), 1,
      aux_sym__macro_tuple_arg_nest,
  [454] = 5,
    ACTIONS(104), 1,
      anon_sym_RBRACE,
    ACTIONS(160), 1,
      aux_sym_lua_block_token1,
    ACTIONS(163), 1,
      anon_sym_LPAREN2,
    ACTIONS(166), 1,
      anon_sym_LBRACE,
    STATE(32), 1,
      aux_sym__macro_tuple_arg_nest,
  [470] = 5,
    ACTIONS(143), 1,
      anon_sym_LPAREN2,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    ACTIONS(169), 1,
      anon_sym_RPAREN,
    ACTIONS(171), 1,
      aux_sym_lua_block_token1,
    STATE(35), 1,
      aux_sym__macro_tuple_arg_nest,
  [486] = 5,
    ACTIONS(133), 1,
      anon_sym_LPAREN2,
    ACTIONS(135), 1,
      anon_sym_LBRACE,
    ACTIONS(169), 1,
      anon_sym_RBRACE,
    ACTIONS(173), 1,
      aux_sym_lua_block_token1,
    STATE(36), 1,
      aux_sym__macro_tuple_arg_nest,
  [502] = 5,
    ACTIONS(143), 1,
      anon_sym_LPAREN2,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    ACTIONS(149), 1,
      aux_sym_lua_block_token1,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    STATE(31), 1,
      aux_sym__macro_tuple_arg_nest,
  [518] = 5,
    ACTIONS(131), 1,
      aux_sym_lua_block_token1,
    ACTIONS(133), 1,
      anon_sym_LPAREN2,
    ACTIONS(135), 1,
      anon_sym_LBRACE,
    ACTIONS(175), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      aux_sym__macro_tuple_arg_nest,
  [534] = 5,
    ACTIONS(143), 1,
      anon_sym_LPAREN2,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    ACTIONS(177), 1,
      anon_sym_RPAREN,
    ACTIONS(179), 1,
      aux_sym_lua_block_token1,
    STATE(39), 1,
      aux_sym__macro_tuple_arg_nest,
  [550] = 5,
    ACTIONS(133), 1,
      anon_sym_LPAREN2,
    ACTIONS(135), 1,
      anon_sym_LBRACE,
    ACTIONS(177), 1,
      anon_sym_RBRACE,
    ACTIONS(181), 1,
      aux_sym_lua_block_token1,
    STATE(40), 1,
      aux_sym__macro_tuple_arg_nest,
  [566] = 5,
    ACTIONS(143), 1,
      anon_sym_LPAREN2,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    ACTIONS(149), 1,
      aux_sym_lua_block_token1,
    ACTIONS(183), 1,
      anon_sym_RPAREN,
    STATE(31), 1,
      aux_sym__macro_tuple_arg_nest,
  [582] = 5,
    ACTIONS(131), 1,
      aux_sym_lua_block_token1,
    ACTIONS(133), 1,
      anon_sym_LPAREN2,
    ACTIONS(135), 1,
      anon_sym_LBRACE,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
    STATE(32), 1,
      aux_sym__macro_tuple_arg_nest,
  [598] = 1,
    ACTIONS(185), 5,
      anon_sym_RPAREN,
      aux_sym_lua_block_token1,
      anon_sym_COMMA,
      anon_sym_LPAREN2,
      anon_sym_LBRACE,
  [606] = 1,
    ACTIONS(104), 4,
      anon_sym_RPAREN,
      aux_sym_lua_block_token1,
      anon_sym_LPAREN2,
      anon_sym_LBRACE,
  [613] = 1,
    ACTIONS(185), 4,
      anon_sym_RPAREN,
      aux_sym_lua_block_token1,
      anon_sym_LPAREN2,
      anon_sym_LBRACE,
  [620] = 1,
    ACTIONS(104), 4,
      aux_sym_lua_block_token1,
      anon_sym_LPAREN2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [627] = 1,
    ACTIONS(185), 4,
      aux_sym_lua_block_token1,
      anon_sym_LPAREN2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [634] = 3,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    ACTIONS(189), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym_macro_tuple_args_repeat1,
  [644] = 3,
    ACTIONS(191), 1,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
    ACTIONS(193), 1,
      aux_sym_lua_block_token1,
    STATE(56), 1,
      aux_sym_lua_block_repeat1,
  [654] = 3,
    ACTIONS(195), 1,
      sym__identifier,
    STATE(2), 1,
      sym_macro_identifier_part,
    STATE(6), 1,
      sym_macro_identifier,
  [664] = 3,
    ACTIONS(197), 1,
      anon_sym_RPAREN,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym_macro_tuple_args_repeat1,
  [674] = 3,
    ACTIONS(202), 1,
      anon_sym_RPAREN,
    ACTIONS(204), 1,
      aux_sym_lua_block_token1,
    STATE(50), 1,
      aux_sym_lua_block_repeat1,
  [684] = 3,
    ACTIONS(207), 1,
      aux_sym_lua_block_token1,
    ACTIONS(209), 1,
      anon_sym_DQUOTE2,
    STATE(53), 1,
      aux_sym_lua_block_repeat1,
  [694] = 3,
    ACTIONS(211), 1,
      anon_sym_RPAREN,
    ACTIONS(213), 1,
      aux_sym_lua_block_token1,
    STATE(50), 1,
      aux_sym_lua_block_repeat1,
  [704] = 3,
    ACTIONS(202), 1,
      anon_sym_DQUOTE2,
    ACTIONS(215), 1,
      aux_sym_lua_block_token1,
    STATE(53), 1,
      aux_sym_lua_block_repeat1,
  [714] = 3,
    ACTIONS(218), 1,
      aux_sym_lua_block_token1,
    STATE(47), 1,
      aux_sym_lua_block_repeat1,
    STATE(65), 1,
      sym_lua_block,
  [724] = 3,
    ACTIONS(189), 1,
      anon_sym_COMMA,
    ACTIONS(220), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      aux_sym_macro_tuple_args_repeat1,
  [734] = 3,
    ACTIONS(202), 1,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
    ACTIONS(222), 1,
      aux_sym_lua_block_token1,
    STATE(56), 1,
      aux_sym_lua_block_repeat1,
  [744] = 3,
    ACTIONS(225), 1,
      aux_sym_lua_block_token1,
    ACTIONS(227), 1,
      anon_sym_DQUOTE2,
    STATE(51), 1,
      aux_sym_lua_block_repeat1,
  [754] = 3,
    ACTIONS(229), 1,
      aux_sym_lua_block_token1,
    STATE(52), 1,
      aux_sym_lua_block_repeat1,
    STATE(66), 1,
      sym_lua_inline,
  [764] = 2,
    ACTIONS(195), 1,
      sym__identifier,
    STATE(7), 1,
      sym_macro_identifier_part,
  [771] = 2,
    ACTIONS(231), 1,
      sym__identifier,
    STATE(11), 1,
      sym_macro_identifier_part,
  [778] = 1,
    ACTIONS(197), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [783] = 2,
    ACTIONS(233), 1,
      anon_sym_LPAREN,
    ACTIONS(235), 1,
      sym_lua_line,
  [790] = 2,
    ACTIONS(231), 1,
      sym__identifier,
    STATE(10), 1,
      sym_macro_identifier_part,
  [797] = 1,
    ACTIONS(237), 1,
      ts_builtin_sym_end,
  [801] = 1,
    ACTIONS(239), 1,
      anon_sym_DOLLAR_DOLLAR_DOLLAR,
  [805] = 1,
    ACTIONS(241), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 64,
  [SMALL_STATE(6)] = 79,
  [SMALL_STATE(7)] = 100,
  [SMALL_STATE(8)] = 115,
  [SMALL_STATE(9)] = 137,
  [SMALL_STATE(10)] = 159,
  [SMALL_STATE(11)] = 172,
  [SMALL_STATE(12)] = 185,
  [SMALL_STATE(13)] = 198,
  [SMALL_STATE(14)] = 209,
  [SMALL_STATE(15)] = 220,
  [SMALL_STATE(16)] = 239,
  [SMALL_STATE(17)] = 250,
  [SMALL_STATE(18)] = 261,
  [SMALL_STATE(19)] = 272,
  [SMALL_STATE(20)] = 283,
  [SMALL_STATE(21)] = 300,
  [SMALL_STATE(22)] = 311,
  [SMALL_STATE(23)] = 328,
  [SMALL_STATE(24)] = 339,
  [SMALL_STATE(25)] = 350,
  [SMALL_STATE(26)] = 366,
  [SMALL_STATE(27)] = 382,
  [SMALL_STATE(28)] = 398,
  [SMALL_STATE(29)] = 406,
  [SMALL_STATE(30)] = 422,
  [SMALL_STATE(31)] = 438,
  [SMALL_STATE(32)] = 454,
  [SMALL_STATE(33)] = 470,
  [SMALL_STATE(34)] = 486,
  [SMALL_STATE(35)] = 502,
  [SMALL_STATE(36)] = 518,
  [SMALL_STATE(37)] = 534,
  [SMALL_STATE(38)] = 550,
  [SMALL_STATE(39)] = 566,
  [SMALL_STATE(40)] = 582,
  [SMALL_STATE(41)] = 598,
  [SMALL_STATE(42)] = 606,
  [SMALL_STATE(43)] = 613,
  [SMALL_STATE(44)] = 620,
  [SMALL_STATE(45)] = 627,
  [SMALL_STATE(46)] = 634,
  [SMALL_STATE(47)] = 644,
  [SMALL_STATE(48)] = 654,
  [SMALL_STATE(49)] = 664,
  [SMALL_STATE(50)] = 674,
  [SMALL_STATE(51)] = 684,
  [SMALL_STATE(52)] = 694,
  [SMALL_STATE(53)] = 704,
  [SMALL_STATE(54)] = 714,
  [SMALL_STATE(55)] = 724,
  [SMALL_STATE(56)] = 734,
  [SMALL_STATE(57)] = 744,
  [SMALL_STATE(58)] = 754,
  [SMALL_STATE(59)] = 764,
  [SMALL_STATE(60)] = 771,
  [SMALL_STATE(61)] = 778,
  [SMALL_STATE(62)] = 783,
  [SMALL_STATE(63)] = 790,
  [SMALL_STATE(64)] = 797,
  [SMALL_STATE(65)] = 801,
  [SMALL_STATE(66)] = 805,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_identifier, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_identifier, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_identifier, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_identifier, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_macro_identifier_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_macro_identifier_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_identifier_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_identifier_part, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_identifier_part, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 2, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_identifier, 4, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_identifier, 4, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_identifier, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_identifier, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lua, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__lua, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lua, 3, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__lua, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lua, 4, 0, 1),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__lua, 4, 0, 1),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_string_arg, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_string_arg, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_tuple_args, 3, 0, 3),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_tuple_args, 3, 0, 3),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 2, 0, 0),
  [106] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 2, 0, 0), SHIFT_REPEAT(20),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 2, 0, 0), SHIFT_REPEAT(26),
  [112] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 2, 0, 0), SHIFT_REPEAT(27),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_string_arg, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_string_arg, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_tuple_arg, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_tuple_args, 4, 0, 1),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_tuple_args, 4, 0, 1),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_tuple_args, 2, 0, 2),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_tuple_args, 2, 0, 2),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [151] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 2, 0, 0), SHIFT_REPEAT(31),
  [154] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 2, 0, 0), SHIFT_REPEAT(33),
  [157] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 2, 0, 0), SHIFT_REPEAT(34),
  [160] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 2, 0, 0), SHIFT_REPEAT(32),
  [163] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 2, 0, 0), SHIFT_REPEAT(37),
  [166] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 2, 0, 0), SHIFT_REPEAT(38),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__macro_tuple_arg_nest, 3, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lua_block, 1, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_macro_tuple_args_repeat1, 2, 0, 0),
  [199] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_macro_tuple_args_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_lua_block_repeat1, 2, 0, 0),
  [204] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_lua_block_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lua_inline, 1, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [215] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_lua_block_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [222] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_lua_block_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [225] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [235] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [237] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lpp(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lpp",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
