$ -- Not really a test file, moreso for me to mess with temp ideas
$ local lpp = require "lpp"

$$$

local test = function()
  local sec = lpp.getSectionAfterMacro()

  sec:insertString(0, "hey")
end

local import = function(path)
  local result = lpp.processFile(path)

  local expansion = lpp.MacroExpansion.new()
  expansion:pushBack(
    lpp.MacroPart.new(
      path, 0, 0, result))

  return result
end

$$$


int main()
{
  @test
}
@import "tests/import/apple.lpp"

