$ -- Not really a test file, moreso for me to mess with temp ideas
$ local lpp = require "lpp"
$ local List = require "list"
$ require "lppclang" .init("../lppclang/build/debug/liblppclang.so")

$$$

lpp.registerFinal(function(result)
  local makedeps = 
    lpp.clang.generateMakeDepFile(
      result, 
      List { "-I../iro" })
  
  for f in makedeps:gmatch("%S+") do
    if f:sub(-1) == ":" or f == "\\" then
      goto continue
    end

    lpp.addDependency(f)
    
    ::continue::
  end
end)

$$$

#include "iro/containers/array.h"

int main()
{
}

