$ -- Not really a test file, moreso for me to mess with temp ideas
$ local lpp = require "lpp"
$ -- require "lppclang" .init("../lppclang/build/debug/liblppclang.so")

$ local okay = function() error "ugh" end
$ local ok = function() okay() end
$ local yep = function() ok() end

$$$

local bigFunc = function()





end

$$$

$ local hello = function()
    @yep
$ end

$ local thing = function()
$   hello()
$ end 

$ local test = function(T)
struct Array_$(T) 
{
	$(T)* ptr;
	u32 count;
	u32 space;
	u32 test;
	u32 asodmasd
	asdasda
	da
	d

	ad
	d
};
$ end

$ local anotherTest = function()
struct Hey
{
	int goodbye;
	int hello;
	int goodbye;
	int hello;
};
$ end

$ hello()

$$$

local bigFunc = function()





end

$$$
